### ISSUE TITLE
其他问题

### ISSUE THREAD

**Issue by xiaoba28** [hetutu5238/vue-demo#1]
博主 你这个demo和https://www.cnblogs.com/hetutu-5238/p/9456016.html这篇文章上的内容为啥不一样 另外后台是不是少了mapper映射类代码

**Comment by hetutu5238** [comment]
后台我简写了一下，文章着重点为前端。后台网上网上教程非常多了，我没必要再赘述

**Comment by wangguangzhong** [comment]
1
